#!/bin/bash
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &
node main upload &